name: Docker
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  push_docker:
    name: Push Docker Image
    runs-on: ubuntu-22.04
    timeout-minutes: 720
    strategy:
      matrix:
        rosdistro: [humble]
        arch: [arm64]
    steps:
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: false

      - name: Install docker for ubuntu runner
        uses: docker/setup-buildx-action@v3

      - name: Install QEMU
        uses: docker/setup-qemu-action@v3

      - uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: ZYUMON TIME
        run:
          docker buildx build --platform linux/arm64/v8,linux/amd64 -t ghcr.io/TakanoTaiga/scenario_simulator_v2:humble --build-arg ROS_DISTRO=humble --push .
          
      # - name: ZYUMON TIME
      #   run:
      #     docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
      #     docker buildx create --use
      #     docker buildx inspect --bootstrap

      # - name: Build (${{ matrix.arch }})
      #   uses: docker/bake-action@v5
      #   with:
      #     files: |
      #       ./docker-bake.hcl
      #     push: false
